site_name: Énumération

nav:
  - 'Énumération': 'index.md'


theme:
  name: material
  font: false
  language: fr
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate
    - header.autohide

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mode sombre

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Mode clair


markdown_extensions:
  - abbr
  - def_list
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: ⚓︎
      toc_depth: 3


plugins:
  - search

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:franck.chambon@ac-aix-marseille.fr
      name: Écrire à l'auteur
