site_name: Mathématiques et NSI
site_url: https://marzikill.github.io/
repo_url: https://github.com/marzikill/marzikill.github.io
edit_uri: tree/master/docs/
site_description: Notes de cours
copyright: |
  Copyleft 🄯 2021 <a href="https://gitlab.com/ens-fr" target="_blank" rel="noopener">Florian Picard</a>
docs_dir: docs

# ceci est un commentaire

nav:
  - 'Énumération': 'index.md'
  - 'nb triangles': '1.triangles/triangles.md'
  - 'nb pavages': '2.pavages/pavages.md'
  - 'nb murs en brique': '3.mur_brique/mur_brique.md'
  - 'nb premiers': '4.arith/arith.md'
  - 'marche aléatoire': '5.marche_aléatoire/marche.md'


theme:
    name: material
    font: false                     # RGPD ; pas de fonte Google
    language: fr                    # français
    palette:                        # Palettes de couleurs jour/nuit
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: indigo
        accent: indigo
        toggle:
            icon: material/weather-sunny
            name: Passer au mode nuit
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: blue
        accent: blue
        toggle:
            icon: material/weather-night
            name: Passer au mode jour
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.expand
        - navigation.top
        - toc.integrate
        - header.autohide


markdown_extensions:
    - meta
    - abbr

    - def_list                      # Les listes de définition.
    - attr_list                     # Un peu de CSS et des attributs HTML.
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    - admonition                    # Blocs colorés  !!! info "ma remarque"
    - pymdownx.details              #   qui peuvent se plier/déplier.
    - pymdownx.caret                # Passage ^^souligné^^ ou en ^exposant^.
    - pymdownx.mark                 # Passage ==surligné==.
    - pymdownx.tilde                # Passage ~~barré~~ ou en ~indice~.
    - pymdownx.highlight            # Coloration syntaxique du code
    - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
    - pymdownx.snippets             # Inclusion de fichiers externe.
    - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    false   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
    - pymdownx.tabbed               # Volets glissants.  === "Mon volet"
    - pymdownx.superfences          # Imbrication de blocs.
    - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
    - pymdownx.emoji:               # Émojis  :boom:
        emoji_index:     !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg


    - pymdownx.arithmatex:
        generic: true
    - toc:
        permalink: ⚓︎
        toc_depth: 3

extra:
    social:
        - icon: fontawesome/brands/gitlab
          link: https://gitlab.com/ens-fr
          name: Enseignement en français

        - icon: fontawesome/brands/discourse
          link: https://mooc-forums.inria.fr/moocnsi/
          name: Le forum des enseignants de NSI

        - icon: fontawesome/brands/linux
          link: https://linuxfr.org/
          name: Promouvoir les Logiciels libres

        - icon: fontawesome/brands/wikipedia-w
          link: https://fr.wikipedia.org
          name: L'encyclopédie libre que chacun peut améliorer

        - icon: fontawesome/solid/paper-plane
          link: mailto:franck.chambon@ac-aix-marseille.fr
          name: Écrire à l'auteur
    site_url: https://ens-fr.gitlab.io/mkdocs/


plugins:
  - search
  - macros

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@8.9.2/dist/mermaid.min.js
  - javascripts/mermaid.js

extra_css:
  - stylesheets/extra.css


